# Generated by Django 4.1.1 on 2025-10-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simple_analytics", "0003_visitperpage_user_agent"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="visitperpage",
            constraint=models.UniqueConstraint(
                fields=["date", "page", "method", "username", "origin", "user_agent"],
                name="unique_visit_per_page",
            ),
        ),
    ]
