# Generated by Django 5.0.2 on 2025-10-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_analytics", "0004_unique_visit_per_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitperpage",
            name="page",
            field=models.CharField(max_length=250),
        ),
    ]
